name: AuditExport Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o dist/auditexport-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/auditexport

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: auditexport-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*
