package assertions

import (
	"auditexport/internal/run"
	"fmt"
	"os"
)

func WriteChangeManagementAssertions(total int) error {

	content := fmt.Sprintf(`
SOC 2 Change Management Assertions
=================================

Control: CC8.1

Assertions:
-----------
✔ All production changes require a pull request
✔ All pull requests require approval
✔ All merges require successful CI execution
✔ Direct pushes to protected branches are prevented

Validated Changes:
------------------
Total compliant production changes: %d

Evidence Source:
----------------
- GitHub Pull Requests
- GitHub Actions Workflow Runs
- Branch Protection Rules

Generated by AuditExport (SOC 2 Pro)
`, total)

	return os.WriteFile(
		run.EvidencePath("summaries", "soc2_change_management_assertions.txt"),
		[]byte(content),
		0644,
	)
}
