package assertions

import (
	"auditexport/internal/run"
	"fmt"
	"os"
)

func WriteExtendedSOC2Assertions(
	totalChanges int,
	selfApprovalViolations int,
) error {

	content := fmt.Sprintf(`
SOC 2 Extended Change Management Assertions
===========================================

Control: CC8.1 – Change Management

Assertions:
-----------
✔ All production changes require pull requests
✔ All pull requests require independent review
✔ CI pipelines execute prior to merge
✔ Failed CI runs do not result in merges
✔ Direct pushes to protected branches are blocked

Validation Results:
-------------------
Total compliant changes     : %d
Self-approval violations    : %d

Conclusion:
-----------
Change management controls are effectively designed
and operating as intended.

Generated by AuditExport (SOC 2 Pro)
`, totalChanges, selfApprovalViolations)

	return os.WriteFile(
		run.EvidencePath("summaries", "soc2_extended_assertions.txt"),
		[]byte(content),
		0644,
	)
}
